In [1]:
import numpy as np 
import pandas as pd 
import json

path1 = '/home/pib3/Projetos/tuh_eeg_epilepsy/codes/docs/epilepsy/'
path2 = '/home/pib3/Projetos/tuh_eeg_epilepsy/codes/docs/no_epilepsy/'

file1w = '01_tcp_ar.json'
file2w = '02_tcp_le.json'
file3w = '03_tcp_ar_a.json'

file1n = '01_tcp_ar.json'
file2n = '02_tcp_le.json'
file3n = '03_tcp_ar_a.json'

with open(path1+file1w) as json_file:
    data1w = json.load(json_file)
    
with open(path1+file2w) as json_file:
    data2w = json.load(json_file)
    
with open(path1+file3w) as json_file:
    data3w = json.load(json_file)
    
with open(path2+file1n) as json_file:
    data1n = json.load(json_file)
    
with open(path2+file2n) as json_file:
    data2n = json.load(json_file)
    
with open(path2+file3n) as json_file:
    data3n = json.load(json_file)

In [2]:
aux1w = pd.DataFrame(data1w)
aux2w = pd.DataFrame(data2w)
aux3w = pd.DataFrame(data3w)

aux1n = pd.DataFrame(data1n)
aux2n = pd.DataFrame(data2n)
aux3n = pd.DataFrame(data3n)

print(np.unique(aux1n['montage'],return_counts=True)[1])
print(np.unique(aux2n['montage'],return_counts=True)[1])
print(np.unique(aux3n['montage'],return_counts=True)[1])
np.unique(aux1n['montage'])[2]

[  2  64 153  20   2   2   1   1   1]
[ 1 36]
[5]


['EEG FP1-REF',
 'EEG FP2-REF',
 'EEG F3-REF',
 'EEG F4-REF',
 'EEG C3-REF',
 'EEG C4-REF',
 'EEG P3-REF',
 'EEG P4-REF',
 'EEG O1-REF',
 'EEG O2-REF',
 'EEG F7-REF',
 'EEG F8-REF',
 'EEG T3-REF',
 'EEG T4-REF',
 'EEG T5-REF',
 'EEG T6-REF',
 'EEG A1-REF',
 'EEG A2-REF',
 'EEG FZ-REF',
 'EEG CZ-REF',
 'EEG PZ-REF',
 'EEG ROC-REF',
 'EEG LOC-REF',
 'EEG EKG1-REF',
 'EMG-REF',
 'EEG 26-REF',
 'EEG 27-REF',
 'EEG 28-REF',
 'EEG 29-REF',
 'EEG 30-REF',
 'EEG T1-REF',
 'EEG T2-REF',
 'PHOTIC-REF',
 'IBI',
 'BURSTS',
 'SUPPR']

In [3]:
print(aux1w.shape)
print(aux2w.shape)
print(aux3w.shape)
master = pd.concat([aux1w,aux2w,aux3w,aux1n,aux2n,aux3n])
master.shape

(997, 5)
(99, 5)
(205, 5)


(1589, 5)

In [4]:
# Epilepsy
y1 = np.zeros(aux1w.shape[0]+aux2w.shape[0]+aux3w.shape[0]).astype(int) # Epilepsy
#no epilepsy
y2 = np.ones(aux1n.shape[0]+aux2n.shape[0]+aux3n.shape[0]).astype(int)


y = np.hstack((y1,y2))
master['epilepsy'] = y

In [5]:
master.head(3)

path  \
0  ./01_tcp_ar/087/00008794/s002_2012_05_22/00008...   
1  ./01_tcp_ar/087/00008794/s001_2012_05_17/00008...   
2  ./01_tcp_ar/087/00008754/s001_2012_04_06/00008...   

                                             montage  frequence  nchan  \
0  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...      250.0     30   
1  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...      250.0     30   
2  [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...      250.0     30   

    shape  epilepsy  
0  311500         0  
1  303500         0  
2  450750         0

In [6]:
np.unique(master['frequence'],return_counts=True)

(array([250., 256., 400., 512.]), array([628, 772,  62, 127]))

In [7]:
aux1 = master[master['frequence']==250.0]
aux2 = master[master['frequence']==256.0]


In [8]:
print(aux1[aux1['epilepsy']==0].shape)
print(aux1[aux1['epilepsy']==1].shape)

(352, 6)
(276, 6)


In [9]:
print(aux2[aux2['epilepsy']==0].shape)
print(aux2[aux2['epilepsy']==1].shape)

(765, 6)
(7, 6)


#### Vamos usar eeg's com Fs = 250

In [10]:
master_aux = master[master['frequence']==256.0]
master_aux.shape

(772, 6)

In [11]:
monts = np.unique(master_aux['montage'],return_counts=True)
monts[1]

array([137, 106,  60,  20,   3, 148, 263,   3,   1,  31])

### Mais análise de montagens

In [12]:
#[4,11,12] - 250
#[5,6,7,8,9] - 256
monts[0][9]

['EEG FP1-REF',
 'EEG FP2-REF',
 'EEG F3-REF',
 'EEG F4-REF',
 'EEG C3-REF',
 'EEG C4-REF',
 'EEG P3-REF',
 'EEG P4-REF',
 'EEG O1-REF',
 'EEG O2-REF',
 'EEG F7-REF',
 'EEG F8-REF',
 'EEG T3-REF',
 'EEG T4-REF',
 'EEG T5-REF',
 'EEG T6-REF',
 'EEG T1-REF',
 'EEG T2-REF',
 'EEG FZ-REF',
 'EEG CZ-REF',
 'EEG PZ-REF',
 'EEG EKG1-REF',
 'EMG-REF',
 'EEG A1-REF',
 'EEG A2-REF',
 'EEG 31-REF',
 'EEG 32-REF',
 'IBI',
 'BURSTS',
 'SUPPR']

In [114]:
for i in range(len(monts[0][-2])):
    if 'EEG' in monts[0][-2][i]:
        monts[0][-2][i] = monts[0][-2][i].replace('EEG','')
    if '-REF' in monts[0][-2][i]:
        monts[0][-2][i] = monts[0][-2][i].replace('-REF','')

for i in range(len(monts[0][-3])):
    if 'EEG' in monts[0][-3][i]:
        monts[0][-3][i] = monts[0][-3][i].replace('EEG','')
    if '-REF' in monts[0][-3][i]:
        monts[0][-3][i] = monts[0][-3][i].replace('-REF','')    
        
#print(monts[0][-2])
#print(monts[0][-3])

In [13]:
len(list(master_aux['montage']))# == monts[0][-2]

772

In [15]:
index = []

In [16]:
l = [5,6,7,8,9]
for i in range(len(list(master['montage']))):
    if list(master['montage'])[i] == np.unique(aux1n['montage'])[2]:#monts[0][9]:
        index.append(i)

len(index)

296

In [17]:
master_aux2 = master.iloc[index,:]
master_aux2.shape

(296, 6)

In [18]:

np.unique(master_aux2['montage'])
# freq512 = master[master['frequence']==512.0]
# freq512[freq512['epilepsy']==1].shape

array([list(['EEG FP1-REF', 'EEG FP2-REF', 'EEG F3-REF', 'EEG F4-REF', 'EEG C3-REF', 'EEG C4-REF', 'EEG P3-REF', 'EEG P4-REF', 'EEG O1-REF', 'EEG O2-REF', 'EEG F7-REF', 'EEG F8-REF', 'EEG T3-REF', 'EEG T4-REF', 'EEG T5-REF', 'EEG T6-REF', 'EEG A1-REF', 'EEG A2-REF', 'EEG FZ-REF', 'EEG CZ-REF', 'EEG PZ-REF', 'EEG ROC-REF', 'EEG LOC-REF', 'EEG EKG1-REF', 'EMG-REF', 'EEG 26-REF', 'EEG 27-REF', 'EEG 28-REF', 'EEG 29-REF', 'EEG 30-REF', 'EEG T1-REF', 'EEG T2-REF', 'PHOTIC-REF', 'IBI', 'BURSTS', 'SUPPR'])],
      dtype=object)

In [19]:
np.unique(master_aux2['frequence'])

array([250.])

In [20]:
np.unique(master_aux2['epilepsy'])

array([0, 1])

In [21]:
print(master_aux2[master_aux2['epilepsy']==0].shape)
print(master_aux2[master_aux2['epilepsy']==1].shape)

(143, 6)
(153, 6)


In [22]:
master_aux2.columns

Index(['path', 'montage', 'frequence', 'nchan', 'shape', 'epilepsy'], dtype='object')

In [23]:
np.unique(master_aux2['shape'])

array([   1250,    1500,    2000,    2250,    2500,    2750,    3000,
          3250,    3500,    3750,    4000,    4250,    4500,    4750,
          5000,    5250,    5500,    5750,    6000,    6250,    6500,
          7500,    8500,    8750,    9000,    9250,    9750,   10250,
         10500,   11000,   11750,   12000,   12250,   12750,   13500,
         14250,   14500,   14750,   15250,   16250,   16500,   17750,
         19750,   20000,   20250,   23250,   23500,   24750,   26500,
         28250,   29750,   32250,   34750,   35500,   36500,   36750,
         37000,   37500,   39250,   39500,   40000,   40250,   41250,
         42500,   43500,   50750,   55000,   55750,   57000,   59000,
         59250,   60250,   60750,   61000,   63250,   72000,   74750,
         75000,   76250,   96000,  103250,  113000,  115000,  117500,
        123500,  126250,  133250,  136500,  144000,  148500,  150250,
        150500,  163750,  166750,  179500,  183000,  185000,  213250,
        240500,  242

In [25]:
master_aux2.iloc[0]

path         ./01_tcp_ar/103/00010387/s001_2013_06_04/00010...
montage      [EEG FP1-REF, EEG FP2-REF, EEG F3-REF, EEG F4-...
frequence                                                  250
nchan                                                       36
shape                                                   342500
epilepsy                                                     0
Name: 20, dtype: object

In [36]:
master_aux2.to_csv('data1.csv')