# Definindo montages mais frequentes

In [11]:
import numpy as np 
import pandas as pd 
import json

path1 = '/home/pib3/Projetos/tuh_eeg_epilepsy/codes/docs/epilepsy/'
path2 = '/home/pib3/Projetos/tuh_eeg_epilepsy/codes/docs/no_epilepsy/'

In [12]:
file1w = '01_tcp_ar.json'
file2w = '02_tcp_le.json'
file3w = '03_tcp_ar_a.json'

file1n = '01_tcp_ar.json'
file2n = '02_tcp_le.json'
file3n = '03_tcp_ar_a.json'

with open(path1+file1w) as json_file:
    data1w = json.load(json_file)
    
with open(path1+file2w) as json_file:
    data2w = json.load(json_file)
    
with open(path1+file3w) as json_file:
    data3w = json.load(json_file)
    
with open(path2+file1n) as json_file:
    data1n = json.load(json_file)
    
with open(path2+file2n) as json_file:
    data2n = json.load(json_file)
    
with open(path2+file3n) as json_file:
    data3n = json.load(json_file)
    


In [13]:
montages1w = data1w['montage']
montages2w = data2w['montage']
montages3w = data3w['montage']

montages1n = data1n['montage']
montages2n = data2n['montage']
montages3n = data3n['montage']
#montages.extend(data2['montage'])
#montages.extend(data3['montage'])
#np.unique(montages,return_counts=True)
#len(montages)

In [16]:
print("\nEpilepsy")
print(np.unique(montages1w,return_counts=True)[1])
print(np.unique(montages2w,return_counts=True)[1])
print(np.unique(montages3w,return_counts=True)[1])

print("\nNo Epilepsy")
print(np.unique(montages1n,return_counts=True)[1])
print(np.unique(montages2n,return_counts=True)[1])
print(np.unique(montages3n,return_counts=True)[1])


Epilepsy
[  1 103 143   6   8 152 104  59  20   3  15 349   3  31]
[ 9 80  6  4]
[ 56   1 148]

No Epilepsy
[  2  64 153  20   2   2   1   1   1]
[ 1 36]
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]


In [17]:
# MONTAGENS A SEREM USADAS
mont1w = np.unique(montages1w,return_counts=True)[0][-3]
mont2w = np.unique(montages2w,return_counts=True)[0][1]
mont3w = np.unique(montages3w,return_counts=True)[0][-1]
#print(len(mont1),len(mont2),len(mont3))
mont1n = np.unique(montages1n,return_counts=True)[0][-3]
#mont2w = np.unique(montages2w,return_counts=True)[0]
#mont3w = np.unique(montages3w,return_counts=True)[0]

In [200]:
# mont1
# del mont1[-5:]
# mont1 = [mont1[i][4:]for i in range(len(mont1))]
# mont1 = [mont1[i].replace('-REF','') for i in range(len(mont1))]
# mont1

In [201]:
# mont2
# mont2 = mont2[:-16]
# mont2 = [mont2[i][4:].replace('-LE','') for i in range(len(mont2))]
# mont2

In [202]:
#mont3
# mont3 = mont3[:-8]
# mont3 = [mont3[i][4:]for i in range(len(mont3))]
# mont3 = [mont3[i].replace('-REF','') for i in range(len(mont3))]
# mont3

In [21]:
freq1w = data1w['frequence']
freq2w = data2w['frequence']
freq3w = data3w['frequence']

freq1n = data1n['frequence']
freq2n = data2n['frequence']
freq3n = data3n['frequence']

In [23]:
#FREQUENCIA AMOSTRAL DE EEG
print("\nEpilepsy")
print(np.unique(freq1w,return_counts=True))
print(np.unique(freq2w,return_counts=True))
print(np.unique(freq3w,return_counts=True))
# https://www.geeksforgeeks.org/python-pandas-dataframe-where/
print("\nNo Epilepsy")
print(np.unique(freq1n,return_counts=True))
print(np.unique(freq2n,return_counts=True))
print(np.unique(freq3n,return_counts=True))


Epilepsy
(array([250., 256., 512.]), array([253, 617, 127]))
(array([250.]), array([99]))
(array([256., 400.]), array([148,  57]))

No Epilepsy
(array([250., 256.]), array([239,   7]))
(array([250.]), array([37]))
(array([400.]), array([5]))


In [10]:
import numpy as np

import pandas as pd


df = pd.DataFrame(np.arange(1,10).reshape(3,3))

arr = sparse.coo_matrix(([1,1,1], ([0,1,2], [1,2,0])), shape=(3,3))

df['newcol'] = arr.toarray().tolist()
#arr.toarray().tolist()
#print(df)
type(data1['montage'])

list